services:
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: mlflow-container
    environment:
      - TZ=UTC
    ports:
      - "5001:5000"
    networks:
      - churn_task
    command: mlflow ui --host 0.0.0.0

networks:
  churn_task:
    name: churn_network